name: Daily Portfolio Update

on:
  schedule:
    - cron: "0 13 * * *"  # 22:00 JST daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas matplotlib requests

    - name: Run daily fetch
      run: python daily_fetch.py

    - name: Commit & push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add portfolio_A.html
        git commit -m "Daily auto update"
        git push
